// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh4T8SYeO4GoSn2O6V5tGCrMIXPteg9M0',
    appId: '1:55967801615:web:91cb606bfa5198f7bfde7a',
    messagingSenderId: '55967801615',
    projectId: 'datos-appflutter',
    authDomain: 'datos-appflutter.firebaseapp.com',
    storageBucket: 'datos-appflutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvg9ZQ-0MTe85pr0QRF2HkedGaAOaPh38',
    appId: '1:55967801615:android:8d171b69727032b5bfde7a',
    messagingSenderId: '55967801615',
    projectId: 'datos-appflutter',
    storageBucket: 'datos-appflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyDx2WAs-zNmazNGtZQQeUkGTia0YUEkA',
    appId: '1:55967801615:ios:8b20c60d730e7a0bbfde7a',
    messagingSenderId: '55967801615',
    projectId: 'datos-appflutter',
    storageBucket: 'datos-appflutter.firebasestorage.app',
    iosBundleId: 'com.example.ejemplo0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyDx2WAs-zNmazNGtZQQeUkGTia0YUEkA',
    appId: '1:55967801615:ios:8b20c60d730e7a0bbfde7a',
    messagingSenderId: '55967801615',
    projectId: 'datos-appflutter',
    storageBucket: 'datos-appflutter.firebasestorage.app',
    iosBundleId: 'com.example.ejemplo0',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh4T8SYeO4GoSn2O6V5tGCrMIXPteg9M0',
    appId: '1:55967801615:web:21ae11518724e8d1bfde7a',
    messagingSenderId: '55967801615',
    projectId: 'datos-appflutter',
    authDomain: 'datos-appflutter.firebaseapp.com',
    storageBucket: 'datos-appflutter.firebasestorage.app',
  );

}